apiVersion: "cert-manager.io/v1alpha2"
kind: "ClusterIssuer"
metadata:
  name: "letsencrypt-prod"
  namespace: cert-manager
spec:
  acme:
    email: "kodingwarrior@kakao.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: "letsencrypt-prod"
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: "kong"
