
apiVersion: v1
kind: Service
metadata:
  name: yeemathong-api-service
  namespace: yeemathong
  labels:
    service: yeemathong-api-service
spec:
  type: NodePort
  selector:
    service: yeemathong-api-service
  ports:
    - name: yeemathong-api-service
      port: 8000
      protocol: "TCP"
      targetPort: 8000
