name: Build and Deploy to AWS EKS

on:
  push:
    branches:
      - main

env:
  DATABASE_URL: '${{ secrets.DATABASE_URL }}'
  REDIS_URL: '${{ secrets.REDIS_URL }}'
  SECRET_KEY_BASE: '${{ secrets.SECRET_KEY_BASE }}'
  RAILS_MASTER_KEY: '${{ secrets.RAILS_MASTER_KEY }}'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR (Server)
      id: build-image-server
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: yeemathong
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg DATABASE_URL --build-arg REDIS_URL --build-arg SECRET_KEY_BASE --build-arg RAILS_MASTER_KEY .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Build, tag, and push image to Amazon ECR (Queue)
      id: build-image-queue
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: yeemathong-queue
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -f Dockerfile.sidekiq -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg DATABASE_URL --build-arg REDIS_URL --build-arg SECRET_KEY_BASE --build-arg RAILS_MASTER_KEY .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Enroll Service (Server)
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f deploy/service/yeemathong-api-service.yml

    - name: Enroll Service (Queue)
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f deploy/service/yeemathong-queue-service.yml

    - name: Replace Deployment configuration files (Server)
      uses: danielr1996/envsubst-action@1.0.0
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: yeemathong
        IMAGE_TAG: ${{ github.sha }}
      with:
        input: deploy/deployment/yeemathong-api-deployment.yml.template
        output: deploy/deployment/yeemathong-api-deployment.yml

    - name: Replace Deployment configuration files (Queue)
      uses: danielr1996/envsubst-action@1.0.0
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: yeemathong-queue
        IMAGE_TAG: ${{ github.sha }}
      with:
        input: deploy/deployment/yeemathong-queue-deployment.yml.template
        output: deploy/deployment/yeemathong-queue-deployment.yml

    - name: Enroll Deployment (Server)
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: yeemathong
      with:
        args: apply -f deploy/deployment/yeemathong-api-deployment.yml

    - name: Enroll Deployment (Queue)
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: yeemathong-queue
      with:
        args: apply -f deploy/deployment/yeemathong-queue-deployment.yml

    - name: Wait for Deployment (Server)
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: yeemathong
        SERVICE_NAME: yeemathong-api
      with:
        args: wait deployment.v1.apps/$SERVICE_NAME --for=condition=available --timeout=300s -n yeemathong

    - name: Deploy to Cluster (Server)
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: yeemathong
        SERVICE_NAME: yeemathong-api
      with:
        args: set image deployment.v1.apps/$SERVICE_NAME $ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -n yeemathong

    - name: Deploy to Cluster (Queue)
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: yeemathong-queue
        SERVICE_NAME: yeemathong-queue
      with:
        args: set image deployment.v1.apps/$SERVICE_NAME $ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -n yeemathong

    - name: Setup Ingress
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f deploy/yeemathong-ingress.yml